from lib2to3.pgen2 import pgen
import turtle

pg = turtle.Turtle()
turtle.bgcolor("black")
pg.color("yellow")


def rect():
    pg.pensize(9)
    pg.forward(170)
    pg.left(45)
    pg.forward(6)
    pg.left(45)
    pg.forward(170)
    pg.left(45)
    pg.forward(6)
    pg.left(45)
    pg.forward(330)
    pg.left(45)
    pg.forward(6)
    pg.left(45)
    pg.forward(170)
    pg.left(45)
    pg.forward(6)
    pg.left(45)
    pg.forward(170)

def four_corner_lines():
    pg.pensize(12)
    pg.penup()
    pg.forward(180)
    pg.left(90)
    pg.forward(35)
    pg.left(90)
    pg.pendown()
    pg.forward(12)
    pg.penup()
    pg.forward(344)
    pg.pendown()
    pg.forward(17)
    pg.penup()
    pg.right(90)
    pg.forward(105)
    pg.right(90)
    pg.pendown()
    pg.forward(17)
    pg.penup()
    pg.forward(344)
    pg.pendown()
    pg.forward(12)

def I():
    pg.penup()
    pg.left(180)
    pg.forward(280)
    pg.pendown()
    pg.forward(40)
    pg.left(90)
    pg.forward(100)
    pg.left(180)
    pg.forward(52)
    pg.right(90)
    pg.forward(40)
    pg.left(90)
    pg.forward(47)

def L():
    pg.penup()
    pg.right(90)
    pg.forward(32)
    pg.right(90)
    pg.pendown()
    pg.forward(98)
    pg.left(90)
    pg.forward(40)
    pg.left(90)
    pg.forward(98)

def U():
    pg.penup()
    pg.right(90)
    pg.forward(35)
    pg.pendown()
    pg.forward(45)
    pg.right(90)
    pg.forward(43)
    pg.right(45)
    pg.forward(5)
    pg.right(45)
    pg.forward(40)
    pg.left(90)
    pg.forward(5)
    pg.left(90)
    pg.forward(40)
    pg.right(45)
    pg.forward(5)
    pg.right(45)
    pg.forward(40)
    pg.right(90)
    pg.forward(45)
    pg.right(90)
    pg.forward(96)

def V():
    pg.penup()
    pg.right(180)
    pg.forward(53)
    pg.left(90)
    pg.forward(98)
    pg.pendown()
    pg.forward(25)
    pg.right(90)
    pg.forward(45)
    pg.right(90)
    pg.forward(45)
    pg.right(90)
    pg.forward(95)
    pg.right(90)
    pg.forward(40)


rect()
four_corner_lines()
I()
L()
U()
V()

turtle.done()



